using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using watchtower.Models.CharacterViewer.CharacterStats;

namespace watchtower.Code.CharacterViewer {
    
    public interface ICharacterStatGenerator {

        /// <summary>
        ///     Generate the stats set this generator makes
        /// </summary>
        /// <param name="charID">ID of the character to make the stat for</param>
        /// <returns>
        ///     A new stat generated by this generator, or <c>null</c> if the generation failed
        /// </returns>
        Task<ExtraStatSet?> Generate(string charID);

    }

}
